SHELL:=/bin/bash

all:

MatrixDatabase_assets:
	rsync -avzh --stats --progress areynolds@tools0.altiusinstitute.org:/home/ntripician/slurm/MatrixDatabase ${PWD}

RecommenderDatabase_assets:
	rsync -avzh --stats --progress areynolds@tools0.altiusinstitute.org:/home/ntripician/slurm/RecommenderDatabase ${PWD}

StateScores_assets:
	rsync -avzh --stats --progress areynolds@tools0.altiusinstitute.org:/home/ntripician/StateScores ${PWD}
